name: "Build and Deploy to Netlify - Dev"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to be deployed"
        required: true

jobs:
  build:
    name: Build and Deploy ${{ github.event.repository.name }} to Netlify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: NPM install
        run: npm ci

      - name: Build ${{ github.event.repository.name }}
        run: npm run build

       # ( Build to ./dist or other directory... )
      - name: Deploy ${{ github.event.repository.name }} to Netlify
        id: deploy
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './dist/${{ github.event.repository.name }}/browser'
          # production-branch: main
          # production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploying ${{ github.event.repository.name }} to Netlify"
          netlify-config-path: ./netlify.toml
          enable-github-deployment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
    
      # Set Job Summary
      - name: Job details
        run: |
          echo "Deployed ${{ github.event.repository.name }} to Netlify" >> $GITHUB_STEP_SUMMARY  
          echo "URL: ${{ steps.deploy.outputs.deploy-url }}" >> $GITHUB_STEP_SUMMARY  
