on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find PR Number
        uses: jwalton/gh-find-current-pr@v1
        id: findPr

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Run jest tests
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          prnumber: ${{ steps.findPr.outputs.number }}
          test-script: npm test

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test